# Generated by Django 3.0.5 on 2020-04-24 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='transaction',
            new_name='tr',
        ),
    ]
