# Generated by Django 3.0.5 on 2020-04-24 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200423_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='tr',
            new_name='transaction',
        ),
    ]
