# Generated by Django 3.0.5 on 2020-04-24 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200423_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='transaction_date',
            new_name='balance_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='account',
            name='transaction_amount',
        ),
    ]
