# Generated by Django 3.0.5 on 2020-04-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200423_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
